export const SET_SELECTED_GAME = 'SET_SELECTED_GAME';
export const SET_SELECTED_BET = 'SET_SELECTED_BET';
export const SET_SELECTED_BALLS = 'SET_SELECTED_BALLS';
export const SET_SELECTED_FIRST_BALL_COLOR = 'SET_SELECTED_FIRST_BALL_COLOR';
