export const CHANGE_FIRST_TAB = "CHANGE_FIRST_TAB";
export const CHANGE_SECOND_TAB = "CHANGE_SECOND_TAB";
export const CHANGE_THIRD_TAB = "CHANGE_THIRD_TAB";
export const CHANGE_MOBILE_TAB = "CHANGE_MOBILE_TAB";
export const CHANGE_VIEW_SCREEN = "CHANGE_VIEW_SCREEN";
